name: trigger SIL Kit Adapters Pkg Workflow
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  get-tag-name:
    name: Get the release tag name
    runs-on: 
      group: shared-runners
      labels: Linux
    outputs:
      tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
    steps:
      - name: Get the tag name
        id: get_tag_name
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
  call-packaging-workflow:
    name: Trigger the Debian package workflow
    needs: get-tag-name
    uses: vectorgrp/sil-kit-adapters-pkg/.github/workflows/package-debian.yml@main
    with:
      adapter_name: tap
      tag_name: ${{ needs.get-tag-name.outputs.tag_name }}
    secrets: inherit
  handle-artifacts:
    name: Download the package archive and upload it to the release
    needs: call-packaging-workflow
    runs-on: 
      group: shared-runners
      labels: Linux
    steps:
      - name: Download the package
        id: download-pkg
        uses: actions/download-artifact@v3
      - name: Zip the artifact
        run: |
          rm -f sil-kit-adapter-tap_*.zip
          dir_path=$(find . -maxdepth 1 -name "sil-kit-adapter-tap_*")
          dir_name=$(basename $dir_path)
          zip "${dir_name}.zip" $dir_path/*
      - name: Release the package
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          draft: true
          fail_on_unmatched_files: true
          files: |
            ${{ steps.download-pkg.outputs.download-path }}/sil-kit-adapter-tap_*.zip
